// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package ql

type Article struct {
	Path  string `json:"path"`
	Title string `json:"title"`
	Text  string `json:"text"`
}

type Note struct {
	Name  string `json:"name"`
	Title string `json:"title"`
	Text  string `json:"text"`
}

type Page struct {
	Path  string  `json:"path"`
	Note  *Note   `json:"note"`
	Notes []*Page `json:"notes"`
}
