// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package ql

type Article struct {
	Path  *string `json:"Path"`
	Title *string `json:"Title"`
	Text  *string `json:"Text"`
}

type Note struct {
	Name  *string `json:"Name"`
	Title *string `json:"Title"`
	Text  *string `json:"Text"`
	Notes []*Note `json:"notes"`
}
