[package]
name = "wc-rust"
version = "0.1.0"
authors = ["WooYooWaan <wooyoowaan@gmail.com>"]

[dependencies]


[[bin]]
name = "matrix"
path = "src/main.rs"

[[bin]]
name = "wc"
path = "src/wc.rs"

[[bin]]
name = "httpd"
path = "src/httpd.rs"
